apiVersion: v1
kind: Service
metadata:
  name: ergo-chat-tor
spec:
  selector:
    app: ergo-chat
  ports:
  - port: 6667
    targetPort: 6667
    name: irc
  - port: 8067
    targetPort: 8067
    name: ircws
---
apiVersion: v1
kind: Service
metadata:
  name: ergo-chat
spec:
  selector:
    app: ergo-chat
  ports:
  - port: 6667
    targetPort: 6668
    name: irc
  - port: 8067
    targetPort: 8068
    name: websocket